apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openshift-partner-labs.fullname" . }}-config
  labels:
    {{- include "openshift-partner-labs.labels" . | nindent 4 }}
data:
  config.yaml: |
    credentials:
      google:
        client_id: "${GOOGLE_CLIENT_ID}"
        client_secret: "${GOOGLE_CLIENT_SECRET}"
        redirect_uri: "{{ .Values.config.google.redirectUri }}"
    
    preauthorized:
      emails:
        {{- range .Values.config.preauthorized.emails }}
        - {{ . | quote }}
        {{- end }}
    
    ollama:
      host: {{ .Values.config.ollama.host | quote }}
      chat_model: {{ .Values.config.ollama.chatModel | quote }}
      options:
        {{- toYaml .Values.config.ollama.options | nindent 8 }}