apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openshift-partner-labs.fullname" . }}-secret
  labels:
    {{- include "openshift-partner-labs.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.config.google.clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.config.google.clientSecret | b64enc | quote }}